name: test

on:
  repository_dispatch:
  workflow_dispatch:
  pull_request:

env:
  TZ: Asia/Shanghai

permissions: write-all

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@main
      with:
        submodules: 'true'

    - name: Install Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 22

    - name: Build
      run: |
        make ci
        echo "FILE_DATE=$(date +"%Y%m%d%H%M")" >> $GITHUB_ENV
